import {useEffect,useMemo,useRef,useState} from 'react'
import {Link,NavLink,Route,Routes,useLocation,useNavigate,useParams} from 'react-router-dom'
import {Activity,ArrowRight,Banknote,Bell,Bot,CalendarDays,ChevronRight,Clock,Coins,Crown,Download,ExternalLink,Filter,Gavel,Image,LayoutDashboard,Menu,MessageCircle,Pause,Play,Radio,RotateCcw,Search,Send,ShieldCheck,Sparkles,Timer,TrendingUp,Trophy,Undo2,Users,X,Zap} from 'lucide-react'
import {Area,AreaChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {io} from 'socket.io-client'
import {api,SOCKET_URL} from './api'
import {auctionBids,fixtures,money,players,recentMatches,teams} from './data'
import Admin from './Admin'

const nav=[['/','Home'],['/teams','Teams'],['/players','Players'],['/matches','Matches'],['/gallery','Gallery'],['/rules','Rules']]
const badge=t=><span className="pill">{t}</span>

function Mark(){return <Link className="mark" to="/"><span className="mark-icon">I</span><span><b>ICL</b><small>IEM CRICKET LEAGUE</small></span></Link>}

function Shell({children}){
 const [open,setOpen]=useState(false),loc=useLocation()
 useEffect(()=>{setOpen(false);scrollTo({top:0,behavior:'smooth'})},[loc.pathname])
 return <div className="app"><div className="score-strip"><div className="live-tag"><i/> LIVE</div><b>FAL</b> 142/4 <span>16.2 OV</span><b>ROY</b> need 35 from 22 <Link to="/matches/21">Match centre <ChevronRight size={14}/></Link></div>
 <header><Mark/><nav className={open?'open':''}>{nav.map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}<NavLink className="auction-nav" to="/auction"><Gavel size={16}/> Live auction</NavLink></nav><div className="head-actions"><Link className="icon-btn" to="/dashboard" aria-label="Dashboard"><LayoutDashboard size={19}/></Link><Link className="btn small desktop-login" to="/login">Sign in</Link><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
 <main>{children}</main><Footer/><Chatbot/></div>
}

function Footer(){return <footer><div><Mark/><p>Built for the passion, played for the pride.<br/>The official home of IEM cricket.</p></div><div><b>League</b><Link to="/teams">Teams</Link><Link to="/matches">Fixtures</Link><Link to="/rules">Rules & format</Link></div><div><b>Experience</b><Link to="/auction">Live auction</Link><Link to="/gallery">Gallery</Link><Link to="/dashboard">Team dashboard</Link></div><div><b>Data</b><span className="online"><i/> Systems operational</span><small>Last synced 2 min ago</small></div><div className="copyright">© 2026 IEM Cricket League · Kolkata, India</div></footer>}

const SectionHead=({eyebrow,title,action})=><div className="section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action&&<Link className="text-link" to={action[1]}>{action[0]}<ArrowRight size={16}/></Link>}</div>
const TeamDot=({short})=>{let t=teams.find(x=>x.short===short);return <span className="team-dot" style={{'--team':t?.color}}>{short}</span>}

function Home(){return <>
 <section className="hero"><div className="hero-grid"/><div className="hero-copy"><div className="season"><span/> Season 03 · 2026</div><h1>THE PITCH<br/><em>IS OURS.</em></h1><p>Six teams. One trophy. Every ball matters. Follow the IEM Cricket League live—from the first bid to the final six.</p><div className="hero-actions"><Link className="btn gold" to="/matches"><Radio size={18}/> Follow live</Link><Link className="btn ghost" to="/auction"><Gavel size={18}/> Enter auction room</Link></div><div className="hero-stats"><div><b>06</b><span>TEAMS</span></div><div><b>18</b><span>MATCHES</span></div><div><b>96</b><span>PLAYERS</span></div></div></div><div className="hero-art"><div className="ball-orbit"><span>ICL</span></div><div className="match-chip"><small>NEXT UP · 24 SEP</small><div><TeamDot short="FAL"/><b>VS</b><TeamDot short="TIT"/></div><p>4:00 PM · IEM Main Ground</p></div></div></section>
 <section className="wrap"><SectionHead eyebrow="On the calendar" title="UPCOMING FIXTURES" action={['All fixtures','/matches']}/><div className="fixture-grid">{fixtures.map(f=><Link className="fixture-card" to={`/matches/${f.id}`} key={f.id}><div className="fixture-top"><span>{f.round}</span><b>{f.date}</b></div><div className="versus"><TeamDot short={f.a}/><strong>{f.a}</strong><small>VS</small><strong>{f.b}</strong><TeamDot short={f.b}/></div><div className="fixture-foot"><Clock size={14}/>{f.time}<span>·</span>{f.venue}</div></Link>)}</div></section>
 <section className="wrap standings-block"><SectionHead eyebrow="League standings" title="ROAD TO THE FINAL" action={['Full table','/matches']}/><div className="split"><PointsTable/><div className="form-card"><div className="trophy-mini"><Trophy/></div><span className="eyebrow">Grand finale</span><h3>THE LAST DANCE</h3><p>Top 4 qualify for playoffs. The final takes place under the lights at IEM Main Ground.</p><div className="datebox"><b>04</b><span>OCT<br/>2026</span></div></div></div></section>
 <section className="wrap"><SectionHead eyebrow="Top performers" title="THE LEADERS" action={['All players','/players']}/><div className="leader-grid"><Leader title="ORANGE CAP" icon={<Crown/>} color="#f59e42" data={[players[1],players[0],players[3]]} metric="runs"/><Leader title="PURPLE CAP" icon={<Zap/>} color="#a98bff" data={[players[2],players[5],players[0]]} metric="wickets"/></div></section>
 <section className="auction-cta"><div><span className="eyebrow">Auction live now</span><h2>BUILD YOUR<br/><em>DREAM XI.</em></h2><p>Watch every bid unfold in real time. Live purse updates, instant sold calls and all the drama.</p><Link className="btn gold" to="/auction">Enter the room <ArrowRight size={18}/></Link></div><div className="bid-preview"><span className="live-tag"><i/> LIVE LOT #28</span><div className="avatar big">RG</div><h3>RITWIK GHOSH</h3><p>Batter · Premium</p><small>CURRENT BID</small><strong>₹1,45,000</strong><div className="bidder"><TeamDot short="TIT"/> Kolkata Titans</div></div></section>
 </>}

function PointsTable(){return <div className="table-card"><div className="tr th"><span># TEAM</span><span>P</span><span>W</span><span>L</span><span>NRR</span><span>PTS</span></div>{teams.map((t,i)=><div className="tr" key={t.id}><span><b className="rank">{i+1}</b><TeamDot short={t.short}/><strong>{t.name}</strong></span><span>5</span><span>{t.won}</span><span>{t.lost}</span><span className={t.nrr[0]==='+'?'positive':''}>{t.nrr}</span><span><b>{t.points}</b></span></div>)}</div>}
function Leader({title,icon,color,data,metric}){return <div className="leader-card" style={{'--leader':color}}><div className="leader-title"><span>{icon}</span><b>{title}</b><small>2026</small></div>{data.map((p,i)=><Link to={`/players/${p.id}`} className="leader-row" key={p.id}><b>0{i+1}</b><div className="avatar">{p.avatar}</div><span><strong>{p.name}</strong><small>{p.team}</small></span><em>{p[metric]}<small>{metric==='runs'?' RUNS':' WKTS'}</small></em></Link>)}</div>}

function PageHero({kicker,title,copy,children}){return <section className="page-hero"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{copy}</p>{children}</section>}

function Teams(){return <><PageHero kicker="Six crests · One crown" title="MEET THE TEAMS" copy="The squads, leaders and stories fighting for ICL glory."/><section className="wrap team-grid">{teams.map(t=><Link to={`/teams/${t.id}`} className="team-card" key={t.id} style={{'--team':t.color}}><div className="team-crest">{t.short}</div><span className="pill">{t.players} PLAYERS</span><h2>{t.name}</h2><p>Captain · {t.captain}</p><div className="team-record"><span><b>{t.won}</b>WINS</span><span><b>{t.lost}</b>LOSSES</span><span><b>{t.nrr}</b>NRR</span></div><div className="text-link">View squad <ArrowRight size={16}/></div></Link>)}</section></>}

function TeamDetail(){let {id}=useParams(),t=teams.find(x=>x.id===id)||teams[0];return <><section className="team-detail" style={{'--team':t.color}}><TeamDot short={t.short}/><div><span className="eyebrow">ICL FRANCHISE</span><h1>{t.name}</h1><p>Led by {t.captain} · {t.players} player squad</p></div><a className="btn ghost" href="https://cricheroes.com" target="_blank" rel="noreferrer">View on CricHeroes <ExternalLink size={16}/></a></section><section className="wrap"><div className="metric-grid"><Metric label="POINTS" value={t.points}/><Metric label="NET RUN RATE" value={t.nrr}/><Metric label="PURSE LEFT" value={money(t.purse)}/><Metric label="SQUAD" value={`${t.players}/18`}/></div><SectionHead eyebrow="The squad" title="PLAYING UNIT"/><div className="player-grid">{players.filter((_,i)=>i<4).map(p=><PlayerCard key={p.id} p={{...p,team:t.name}}/>)}</div></section></>}

function Players(){const [q,setQ]=useState(''),[role,setRole]=useState('All');let filtered=players.filter(p=>(role==='All'||p.role===role)&&p.name.toLowerCase().includes(q.toLowerCase()));return <><PageHero kicker="Player directory" title="THE TALENT POOL" copy="Profiles, form, roles and auction values for every registered player."><div className="filters"><label><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search player..."/></label>{['All','Batter','Bowler','All-rounder','Wicketkeeper'].map(r=><button onClick={()=>setRole(r)} className={role===r?'active':''} key={r}>{r}</button>)}</div></PageHero><section className="wrap player-grid">{filtered.map(p=><PlayerCard key={p.id} p={p}/>)}</section></>}
function PlayerCard({p}){return <Link to={`/players/${p.id}`} className="player-card"><div className="avatar player-avatar">{p.avatar}</div><span className="category">{p.category}</span><span className="rating">★ {p.rating}</span><h3>{p.name}</h3><p>{p.role} · {p.style}</p><div className="player-stats"><span><b>{p.runs}</b>RUNS</span><span><b>{p.wickets}</b>WKTS</span><span><b>{p.sr}</b>S/R</span></div><div className="player-team">{p.team}<ChevronRight size={17}/></div></Link>}
function PlayerDetail(){let {id}=useParams(),p=players.find(x=>x.id===id)||players[0];return <><section className="profile-hero"><div className="avatar mega">{p.avatar}</div><div><span className="pill">{p.category}</span><h1>{p.name}</h1><p>{p.role} · {p.style}</p><div className="profile-tags"><span>★ {p.rating} rating</span><span>{p.team}</span></div></div><a className="btn ghost" href="https://cricheroes.com" target="_blank" rel="noreferrer">View on CricHeroes <ExternalLink size={16}/></a></section><section className="wrap"><div className="metric-grid"><Metric label="RUNS" value={p.runs}/><Metric label="WICKETS" value={p.wickets}/><Metric label="STRIKE RATE" value={p.sr}/><Metric label="AUCTION PRICE" value={money(p.price)}/></div><div className="panel prose"><h2>PLAYER PROFILE</h2><p>A composed match-winner with the temperament to perform in pressure situations. Recent form and league consistency make {p.name.split(' ')[0]} a key player to watch this season.</p></div></section></>}

function Matches(){return <><PageHero kicker="Fixtures & results" title="MATCH CENTRE" copy="Every fixture, every scorecard, one place."/><section className="wrap"><SectionHead eyebrow="Next on the pitch" title="UPCOMING"/><div className="fixture-grid">{fixtures.map(f=><Link className="fixture-card" to={`/matches/${f.id}`} key={f.id}><div className="fixture-top"><span>{f.round}</span><b>{f.date}</b></div><div className="versus"><TeamDot short={f.a}/><strong>{f.a}</strong><small>VS</small><strong>{f.b}</strong><TeamDot short={f.b}/></div><div className="fixture-foot"><Clock size={14}/>{f.time} · {f.venue}</div></Link>)}</div><SectionHead eyebrow="Latest action" title="RESULTS"/><div className="results">{recentMatches.map(m=><Link to={`/matches/${m.id}`} key={m.id}><span>{m.date}</span><div><TeamDot short={m.a}/><b>{m.a}</b><strong>{m.as}</strong></div><div><TeamDot short={m.b}/><b>{m.b}</b><strong>{m.bs}</strong></div><em>{m.status}</em><ChevronRight/></Link>)}</div></section></>}
function MatchDetail(){let {id}=useParams(),m=recentMatches.find(x=>String(x.id)===id)||recentMatches[0];return <><section className="page-hero"><span className="live-tag"><i/> SCORECARD</span><h1>{m.a} <em>vs</em> {m.b}</h1><p>{m.date} · IEM Main Ground</p></section><section className="wrap"><div className="scorecard"><div><TeamDot short={m.a}/><h2>{m.a}</h2><strong>{m.as}</strong><span>20 OVERS</span></div><b>VS</b><div><TeamDot short={m.b}/><h2>{m.b}</h2><strong>{m.bs}</strong><span>20 OVERS</span></div><p>{m.status}</p></div><div className="panel"><h3>MATCH SUMMARY</h3><div className="innings"><b>Top batters</b><span>Ritwik Ghosh <strong>74 (46)</strong></span><span>Aryan Bose <strong>52 (31)</strong></span></div><div className="innings"><b>Best bowlers</b><span>Ishan Dutta <strong>3/24</strong></span><span>Shouvik Nandi <strong>2/29</strong></span></div><a className="text-link" href="https://cricheroes.com" target="_blank" rel="noreferrer">View on CricHeroes <ExternalLink size={15}/></a></div></section></>}

function Gallery(){let items=['Opening night under the lights','Falcons celebrate a big wicket','The captains meet','Last over drama','Fans bring the noise','The next generation'];return <><PageHero kicker="Through the lens" title="LEAGUE GALLERY" copy="Big hits, bigger moments, and everything between the wickets."/><section className="wrap gallery-grid">{items.map((x,i)=><article className={`gallery-item g${i}`} key={x}><Image/><div><span>MATCHDAY · 2026</span><h3>{x}</h3></div></article>)}</section></>}
function Rules(){return <><PageHero kicker="How it works" title="RULES & FORMAT" copy="Fast cricket. Fair play. A format built for unforgettable finishes."/><section className="wrap rules-grid"><div className="rules-nav"><a href="#format">01 · Tournament format</a><a href="#match">02 · Match rules</a><a href="#points">03 · Points & NRR</a><a href="#squad">04 · Squad rules</a></div><div className="rules-copy"><Rule n="01" id="format" title="Tournament format">Six teams play a single round-robin league. The top four advance to the playoffs: Qualifier 1, Eliminator, Qualifier 2, and the Grand Final.</Rule><Rule n="02" id="match" title="Match rules">Each match is 20 overs per side. A bowler may deliver a maximum of four overs. Standard ICC T20 playing conditions apply unless stated by the committee.</Rule><Rule n="03" id="points" title="Points & NRR">A win earns 2 points, a tie or no result earns 1, and a loss earns 0. Net run rate breaks ties in the standings.</Rule><Rule n="04" id="squad" title="Squad rules">Squads contain 12–18 players, including at least one wicketkeeper. Teams must remain within their auction purse and role constraints.</Rule></div></section></>}
function Rule({n,title,children,id}){return <article id={id}><span>{n}</span><h2>{title}</h2><p>{children}</p></article>}
function Metric({label,value,sub}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}

function Auction(){
 const [seconds,setSeconds]=useState(18),[paused,setPaused]=useState(false),[bid,setBid]=useState(145000),[bidder,setBidder]=useState('Kolkata Titans'),[history,setHistory]=useState(auctionBids),[sold,setSold]=useState(false),[projector,setProjector]=useState(false),[notice,setNotice]=useState(''),[auctionId,setAuctionId]=useState(null),[teamId,setTeamId]=useState(null),[increment,setIncrement]=useState(10000),socketRef=useRef()
 useEffect(()=>{let mounted=true;const sync=x=>{if(!x||!mounted)return;setAuctionId(x._id);setBid(x.currentBid||x.currentPlayer?.basePrice||0);setIncrement(x.increment||500);setBidder(x.highestBidder?.name||'Waiting for first bid');setHistory(x.bids?.length?x.bids:auctionBids);setPaused(x.status!=='live');let saved;try{saved=JSON.parse(localStorage.getItem('icl_user')||'null')}catch{}setTeamId(saved?.team?._id||saved?.team||x.teams?.[0]?._id||null)};api('/auction/current').then(sync).catch(()=>{});try{let s=io(SOCKET_URL,{transports:['websocket'],timeout:2500,auth:{token:localStorage.getItem('icl_token')}});socketRef.current=s;s.on('timer:tick',x=>setSeconds(x.remaining??x.seconds??x));s.on('bid:new',x=>{setBid(x.amount);setBidder(x.team?.name||x.team||'Team');setHistory(h=>[x,...h])});s.on('player:sold',()=>setSold(true));s.on('auction:state',sync);return()=>{mounted=false;s.close()}}catch{return()=>{mounted=false}}},[])
 useEffect(()=>{if(paused||sold)return;let t=setInterval(()=>setSeconds(s=>s>0?s-1:0),1000);return()=>clearInterval(t)},[paused,sold])
 const demoBid=next=>{setBid(next);setBidder('IEM Falcons');setSeconds(Math.max(seconds,12));setHistory(h=>[{team:'IEM Falcons',amount:next,time:'just now',color:'#f5b941'},...h])}
 const placeBid=async()=>{let next=bid+increment;if(seconds===0||sold)return;try{if(!auctionId||!teamId||!localStorage.getItem('icl_token'))throw new Error('demo');await api(`/auction/${auctionId}/bid`,{method:'POST',body:JSON.stringify({teamId,amount:next})});setNotice(`Bid placed: ${money(next)}`)}catch(error){if(error.message==='demo'){demoBid(next);setNotice(`Demo bid: ${money(next)}`)}else setNotice(error.message)}setTimeout(()=>setNotice(''),2200)}
 const action=async name=>{try{if(auctionId&&localStorage.getItem('icl_token'))await api(`/auction/${auctionId}/actions/${name}`,{method:'POST',body:'{}'});else if(name==='pause'||name==='resume')setPaused(name==='pause');else if(name==='sold')setSold(true);else if(name==='undo')setHistory(h=>h.slice(1))}catch(error){setNotice(error.message);setTimeout(()=>setNotice(''),2200)}}
 return <div className={projector?'projector auction-page':'auction-page'}>{notice&&<div className="toast"><Bell size={17}/>{notice}</div>}{sold&&<div className="sold-overlay" onClick={()=>setSold(false)}><span>SOLD</span><b>{money(bid)}</b><small>{bidder}</small><p>Tap to dismiss</p></div>}
 <div className="auction-bar"><div><span className="live-tag"><i/> LIVE AUCTION</span><b>Season 03 · Main Auction</b></div><div className="auction-tools"><button onClick={()=>setProjector(!projector)}>{projector?'Exit projector':'Projector mode'}</button><span><i/> 248 watching</span></div></div>
 <section className="auction-layout"><aside className="lot-panel"><div className="lot-top"><span>LOT #28</span>{badge('PREMIUM')}</div><div className="avatar auction-avatar">RG</div><h1>RITWIK<br/>GHOSH</h1><p>Batter · Left-hand bat</p><div className="skill-row"><span><b>412</b>Runs</span><span><b>153.2</b>Strike rate</span><span><b>8.8</b>Rating</span></div><div className="base"><span>BASE PRICE</span><b>{money(75000)}</b></div></aside>
  <div className="bid-stage"><div className={`countdown ${seconds<6?'danger':''}`}><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="44"/><circle className="progress" cx="50" cy="50" r="44" style={{strokeDashoffset:276-(276*seconds/30)}}/></svg><strong>{seconds}</strong><small>SECONDS</small></div><p className="going">{seconds<5?'GOING TWICE…':seconds<10?'GOING ONCE…':'BIDDING OPEN'}</p><span className="current-label">CURRENT BID</span><h2>{money(bid)}</h2><div className="highest"><span className="team-dot" style={{'--team':'#50d5c3'}}>TIT</span><span><small>HIGHEST BIDDER</small><b>{bidder}</b></span></div><button className="bid-button" onClick={placeBid}><Gavel/> BID {money(bid+increment)}<small>ONE-TAP BID · +{money(increment)}</small></button><p className="purse-note"><ShieldCheck/> Purse after bid: {money(420000-(bid+increment))}</p></div>
 <aside className="history-panel"><div className="panel-title"><span><Activity/> Bid history</span><b>{history.length} BIDS</b></div><div className="bid-list">{history.map((b,i)=><div key={i}><span className="team-dot" style={{'--team':b.color}}>{b.team.split(' ').map(x=>x[0]).join('').slice(-3)}</span><span><b>{b.team}</b><small>{b.time}</small></span><strong>{money(b.amount)}</strong></div>)}</div><div className="purse-mini"><b>YOUR TEAM · FAL</b><div><span>Available purse</span><strong>{money(420000)}</strong></div><div className="purse-track"><i style={{width:'42%'}}/></div><small>14/18 players · 1 wicketkeeper</small></div></aside></section>
  <div className="auction-control"><button onClick={()=>action(paused?'resume':'pause')}>{paused?<Play/>:<Pause/>}{paused?'Resume':'Pause'}</button><button onClick={()=>action('undo')}><Undo2/>Undo bid</button><button onClick={()=>action('skip')}><ChevronRight/>Skip</button><button onClick={()=>action('reauction')}><RotateCcw/>Re-auction</button><button className="unsold" onClick={()=>action('unsold')}>UNSOLD</button><button className="sold" onClick={()=>action('sold')}>SOLD</button></div></div>
}

const spendData=[{n:'FAL',v:580},{n:'TIT',v:725},{n:'ROY',v:490},{n:'SLS',v:810},{n:'WAR',v:660},{n:'NTK',v:380}]
function Dashboard(){return <><PageHero kicker="Team command centre" title="FALCONS DASHBOARD" copy="Purse, squad balance and auction intelligence at a glance."><div className="dashboard-actions"><button className="btn ghost"><Download size={17}/> Export squad</button><Link className="btn gold" to="/auction"><Gavel size={17}/> Open auction</Link></div></PageHero><section className="wrap"><div className="metric-grid"><Metric label="PURSE AVAILABLE" value="₹4.20L" sub="of ₹10.00L"/><Metric label="SQUAD SIZE" value="14/18" sub="4 slots open"/><Metric label="OVERSEAS" value="2/4" sub="2 slots open"/><Metric label="AVG. RATING" value="8.2" sub="↑ 0.4 vs league"/></div><div className="dashboard-grid"><div className="panel chart-panel"><div className="panel-title"><span><TrendingUp/> Team spend</span><small>₹ thousands</small></div><ResponsiveContainer width="100%" height={270}><AreaChart data={spendData}><defs><linearGradient id="goldGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#f5b941" stopOpacity=".5"/><stop offset="1" stopColor="#f5b941" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#ffffff10" vertical={false}/><XAxis dataKey="n" stroke="#7d8984"/><YAxis stroke="#7d8984"/><Tooltip contentStyle={{background:'#101b17',border:'1px solid #ffffff18'}}/><Area dataKey="v" stroke="#f5b941" fill="url(#goldGrad)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div><div className="panel"><div className="panel-title"><span><Users/> Squad composition</span></div><div className="role-list">{[['Batters',5,'#f5b941'],['Bowlers',4,'#50d5c3'],['All-rounders',4,'#a98bff'],['Wicketkeepers',1,'#ff6b61']].map(([x,n,c])=><div key={x}><i style={{background:c}}/><span>{x}</span><b>{n}</b></div>)}</div><ResponsiveContainer width="100%" height={150}><PieChart><Pie data={[{v:5},{v:4},{v:4},{v:1}]} dataKey="v" innerRadius={44} outerRadius={65} paddingAngle={4}>{['#f5b941','#50d5c3','#a98bff','#ff6b61'].map(c=><Cell key={c} fill={c}/>)}</Pie></PieChart></ResponsiveContainer></div></div><SectionHead eyebrow="Your roster" title="SQUAD"/><div className="player-grid compact">{players.slice(0,4).map(p=><PlayerCard p={{...p,team:'IEM Falcons'}} key={p.id}/>)}</div></section></>}

function Login(){const nav=useNavigate(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);async function submit(e){e.preventDefault();setLoading(true);setError('');try{const result=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('icl_token',result.token);localStorage.setItem('icl_user',JSON.stringify(result.user));nav('/dashboard')}catch(err){setError('Sign in failed. Check the API, database, email and password.')}finally{setLoading(false)}}function demo(){setEmail('admin@icl.test');setPassword('ChangeMe123!')}return <section className="auth-page"><div className="auth-brand"><Mark/><span className="eyebrow">Season 03 · 2026</span><h1>YOUR TEAM.<br/><em>YOUR CALL.</em></h1><p>Access the auction floor, manage your squad, and make every bid count.</p></div><form className="auth-card" onSubmit={submit}><span className="eyebrow">Secure team access</span><h2>WELCOME BACK</h2><p>Sign in with your registered league account.</p><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@iem.edu.in" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required/></label>{error&&<p className="form-error">{error}</p>}<div className="form-row"><label className="check"><input type="checkbox"/> Remember me</label><a href="#">Forgot password?</a></div><button className="btn gold wide" disabled={loading}>{loading?'Signing in…':'Sign in'} <ArrowRight/></button><button type="button" className="demo-login" onClick={demo}>Use demo credentials</button><small>Access is restricted to approved league officials and team managers.</small></form></section>}

function Chatbot(){const [open,setOpen]=useState(false),[messages,setMessages]=useState([{role:'bot',text:'Hi! I’m ICL Assist. Ask me about scores, fixtures, players, auction prices or team purses. Hindi aur Hinglish bhi chalega! 🏏'}]),[q,setQ]=useState(''),[basic,setBasic]=useState(false),[typing,setTyping]=useState(false);async function send(text=q){if(!text.trim())return;setMessages(m=>[...m,{role:'user',text}]);setQ('');setTyping(true);try{let r=await api('/chatbot',{method:'POST',body:JSON.stringify({message:text})});setBasic(Boolean(r.basicMode||r.mode==='basic'));setMessages(m=>[...m,{role:'bot',text:r.answer||r.message}])}catch{setBasic(true);let l=text.toLowerCase(),ans=l.includes('point')?'Falcons lead with 8 points, followed by Titans and Royals on 6.':l.includes('next')||l.includes('match')?'Next match: IEM Falcons vs Kolkata Titans, 24 Sep at 4:00 PM.':l.includes('purse')?'Falcons have ₹4,20,000 remaining in their purse.':l.includes('orange')?'Ritwik Ghosh leads the Orange Cap race with 412 runs.':l.includes('purple')?'Ishan Dutta leads the Purple Cap race with 19 wickets.':'I can help with points table, next match, live score, caps, player prices, team purse, squads, auction status and rules.';setTimeout(()=>setMessages(m=>[...m,{role:'bot',text:ans}]),500)}finally{setTimeout(()=>setTyping(false),520)}}return <><button className="chat-launch" onClick={()=>setOpen(!open)} aria-label="Open ICL assistant">{open?<X/>:<MessageCircle/>}<span>ASK ICL</span></button>{open&&<aside className="chat"><div className="chat-head"><span><Bot/> <b>ICL ASSIST</b></span><span className={basic?'mode basic':'mode'}><i/>{basic?'Basic mode':'AI online'}</span></div><div className="messages">{messages.map((m,i)=><div className={m.role} key={i}>{m.text}</div>)}{typing&&<div className="bot typing"><i/><i/><i/></div>}</div><div className="suggestions">{['Next match?','Points table','Falcons purse'].map(x=><button onClick={()=>send(x)} key={x}>{x}</button>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask anything about ICL..."/><button><Send/></button></form></aside>}</>}

function NotFound(){return <section className="not-found"><span>404</span><h1>OUT!</h1><p>That page has left the field.</p><Link className="btn gold" to="/">Back home</Link></section>}

export default function App(){const loc=useLocation();if(loc.pathname.startsWith('/admin'))return <Routes><Route path="/admin/*" element={<Admin/>}/></Routes>;return <Shell><Routes><Route path="/" element={<Home/>}/><Route path="/teams" element={<Teams/>}/><Route path="/teams/:id" element={<TeamDetail/>}/><Route path="/players" element={<Players/>}/><Route path="/players/:id" element={<PlayerDetail/>}/><Route path="/matches" element={<Matches/>}/><Route path="/matches/:id" element={<MatchDetail/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/rules" element={<Rules/>}/><Route path="/auction" element={<Auction/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/login" element={<Login/>}/><Route path="*" element={<NotFound/>}/></Routes></Shell>}
